### ISSUE TITLE
Add eta' decay mode to hdgeant4

### ISSUE THREAD

**Issue by gleasonc** [JeffersonLab/HDGeant4#106]
Based off the discussion on the google groups from last month (https://groups.google.com/forum/#!topic/gluex-software/VNylmas2Ssg), I wanted to add this as an open issue on the github page.

**Comment by rjones30** [comment]
Collin, yes thanks!
-Richard

**Comment by rjones30** [comment]
Hello Collin and all,

Decays of the etaprime are a part of hdgeant4, and have been since the beginning. I think you meant to post this request on the halld_sim list, for adding this capability to hdgeant. This has now been done, so now both hdgeant and hdgeant4 handle etaprime decays (top 6 decay modes) on a similar basis. 

Reading more carefully back over the mailing list trail linked above, it seems that there is some confusion over what types of particles are supported by hddm. This list is defined in $HALLD_RECON/src/libraries/include/particleTypes.h and includes a long list of unstable mesons, including the EtaPrime, and even a few strange baryons. No change to hddm is needed to extend this list, just a modification to particleTypes.h and additional lines in hdgeant and hdgeant4 codebases to define the active decay modes. In the update I am reporting here, I added code to hdgeant to define decay modes for the EtaPrime and a few other unstable hadrons. This support has been in hdgeant4 since it was in alpha release.

-Richard Jones

**Comment by rjones30** [comment]
Hello Collin and all,

Decays of the etaprime are a part of hdgeant4, and have been since the
beginning. I think you meant to post this request on the halld_sim list,
for adding this capability to hdgeant. This has now been done, so now both
hdgeant and hdgeant4 handle etaprime decays (top 6 decay modes) on a
similar basis.

Reading more carefully back over the mailing list trail linked above, it
seems that there is some confusion over what types of particles are
supported by hddm. This list is defined in
$HALLD_RECON/src/libraries/include/particleTypes.h and includes a long list
of unstable mesons, including the EtaPrime, and even a few strange baryons.
No change to hddm is needed to extend this list, just a modification to
particleTypes.h and additional lines in hdgeant and hdgeant4 codebases to
define the active decay modes. In the update I am reporting here, I added
code to hdgeant to define decay modes for the EtaPrime and a few other
unstable hadrons. This support has been in hdgeant4 since it was in alpha
release.

Unless there is further discussion needed, I think this issue can be closed
on github. Meanwhile, would someone please execute my outstanding pull
request on halld_sim to activate the new coding for EtaPrime in hdgeant?


-Richard Jones
