### ISSUE TITLE
BCAL Photon Gun Updates

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#152]
This is a placeholder for @markdalton's updated BCAL photon gun studies.

**Comment by markdalton** [comment]
Results for 3 simulations done with recent software using mcwrapper, with CUTS card disabled, for hdgeant (HADR1 and HADR4) and hdgeant4.  The simulation weights events with smaller energies and smaller angles higher (logarithmically).  The plots show the ratio of reconstructed energy to thrown energy over the ensemble of events.  The peaks and means of the distributions agree to within 1%, well within the systematic uncertainty of this simple test.  I believe therefore that the overall energy scale factor in hdgeant4 is okay as is.  If we want to be more precise we will need to think carefully how to average over energy and angle, since there is large variation due to leakage.

**Simulation Details**

- Single photon, 1M events, run 30730
- 12 < θ < 90 (log)
- 0.1 GeV < E < 6 GeV (log)
- 50 < Z vertex < 80
- θ reconstructed assuming Z vertex = 65 cm
- recon-2017_01-ver03_16.xml: halld_sim 4.15.0 et al. with recon-2017_01-ver03 and ccdb 1.06.07
- G3 H1 4.15.0
-- hdgeant HADR 1
-- MCwrapper project 1071 (2020-05-20)
- G3 H4 4.15.0
-- hdgeant HADR 4
-- MCwrapper project 1072 (2020-05-20)
- G4 4.15.0
-- hdgeant4
-- MCwrapper project 1073 (2020-05-20)


![EfracN](https://user-images.githubusercontent.com/13302551/82607815-8c013100-9b87-11ea-933b-b43b7faeb85d.png)
![EfracN](https://user-images.githubusercontent.com/13302551/82607879-a89d6900-9b87-11ea-9056-e1e116202fef.png)
![EfracN](https://user-images.githubusercontent.com/13302551/82607904-b226d100-9b87-11ea-86e9-efbac08b9757.png)

**Comment by sdobbs** [comment]
Agreed that the energy scale looks good still, closing.

**Comment by markdalton** [comment]
Simulations done with software version 4.22.0 using mcwrapper for hdgeant (HADR1 and HADR4) and hdgeant4.  hdgeant4 has sub-volume bug fixed (also multi-threading bug but these simulations were run single threaded.)
The simulation weights events with smaller energies and smaller angles higher (logarithmically). The plots show the ratio of reconstructed energy to thrown energy over the ensemble of events. 
The G3 simulations agree extremely well but the G4 simulation has a most probably value 3.2% higher than the G3 simulations.  This is the approximate scale of the correction needed assuming the magnetic field won't change the reconstruction much.

Simulation Details

- Single photon, 1M events, run 30730
- 12 < θ < 90 (log)
- 0.1 GeV < E < 6 GeV (log)
- 50 < Z vertex < 80
- θ reconstructed assuming Z vertex = 65 cm
- version_4.22.0.xml: halld_sim 4.18.0 et al. with recon-2017_01-ver03 and ccdb 1.06.07
- G3 H1 4.18.0
-- hdgeant HADR 1
-- MCwrapper project 1125 (2020-07-07)
- G3 H4 4.18.0
-- hdgeant HADR 4
-- MCwrapper project 1126 (2020-07-07)
- G4 4.18.0
-- hdgeant4
-- MCwrapper project 1127 (2020-07-07)

![EfracN](https://user-images.githubusercontent.com/13302551/87050730-a8573c80-c1cc-11ea-849f-0c7552f5a0df.png)

**Comment by rjones30** [comment]
Mark,

That 3.3% is mostly just the "fudge factor" we have in there from before,
currently 4%. Can I just take that out now, or would you like it reduced to
0.007 ?

-Richard

**Comment by markdalton** [comment]
Richard,
We discussed this at the Calorimetry Meeting and there was a preference to use the determined correction factor 1.008.

**Comment by rjones30** [comment]
Mark

Ok, I will submit a PR for this change shortly.

-Richard J.

**Comment by markdalton** [comment]
It looks like the energy scale is pretty much dead on now.

![EfracN_G3_H1_master_20200710_G4_master_20200710_G3_H4_master_20200710](https://user-images.githubusercontent.com/13302551/87199016-f3ef1080-c2c8-11ea-8e01-8792d8ceb98e.png)
