### ISSUE TITLE
unknown particle type 50 being generated through interactions

### ISSUE THREAD

**Issue by rjones30** [JeffersonLab/HDGeant4#187]
The following error shows up in simulations of events containing certain types of primary particles. This message is going to stderr in hdgeant4.
`ParticleMass: Error: Unknown particle type 50, returning HUGE_VAL..`.
It happens in bursts of order 10 at a time, as if the particle were being generated in bunches. In Geant3, this is the particle type for optical photons, eg. Cerenkov photons or scintillation. I am not aware of any explicit simulation of scintillation light in hdgeant4, so it is probably some residue of G3 code that made it into G4 for the dirc.

**Comment by rjones30** [comment]
The only possible place this could happen is in GlueXSensitiveDetectorFCAL.cc:
`int pmass = track->GetDynamicParticle()->GetMass();`
This raises the question, how does a Cerenkov photon get inside the FCAL? This is a Cerenkov detector, but AFAIK there is no explicit Cerenkov generation implemented for the FCAL in this simulation. The run number is 71000 so there is a DIRC in the geometry, but it should not leak like this unless there is an overlap problem somewhere. Also, why does it only happen for certain kinds of particles in the particle gun sim samples?

- Lambda 
- Klong
- Kshort
- eta
- and more....

but not

- proton
- antiproton
- pi0
- neutron
- and more...

**Comment by jrstevenjlab** [comment]
I suppose one possibility if you see this in the FCAL is the Plexiglas material.  At one point for the DIRC we were considering a plexiglass window instead of fused silica and added optical properties to it.  I see now that they are still in the material definition which is used for the panels in from of the FCAL but not used anywhere in the DIRC

https://github.com/JeffersonLab/hdds/blob/de899d6a375b3ef696eaecb5c2f5b119b757b54b/Material_HDDS.xml#L679

If you remove the optical properties, it you shouldn't get Cherenkov photons even if the CKOV option is on, right?  Why it's different for certain kinds of particles... I have no idea.

**Comment by rjones30** [comment]
Justin,

Ok, that is helpful. My guess is that the plexiglass is in the light guide
at the back of the FCAL blocks. Those are sensitive volumes. I will have a
look at that.

-Richard

**Comment by markdalton** [comment]
The FCAL LED monitoring system is directly upstream of the FCAL blocks.  The are 4 large sheets which each cover a single quadrant of the detector.  The LEDs themselves are at the edge of these sheets and the sheets act to transport the light from the edge to all of the blocks.

**Comment by rjones30** [comment]
Cerenkov light can be produced in the light guides at the back of the fcal. This is normal, but explicit following of CKOV photons should be suppressed in the light guides. I have not seen this warning in a while, closing this issue until it pops up again. -Richard
