### ISSUE TITLE
Time to tag?

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/HDGeant4#25]
Our last tag was applied on March 27. See https://github.com/JeffersonLab/HDGeant4/releases/tag/1.2.0 . Are we ready for a new tag? If not now then soon IMHO.

**Comment by rjones30** [comment]
Mark,

I would like to hear from Sean about whether to suppress writing out the
RFtime take in the hdgeant4 output file. There has been a conversation
about this on the simulations topic because apparently the way I was
handling it was inconsistent with the meaning of the corresponding DRFtime
object in jana, and this was creating confusion. I would prefer to avoid
this and go back to the old behavior of not writing out this tag in
hdgeant4, just like I don't in hdgeant. Just waiting for confirmation from
Sean that this is the way to go, then will check in this change. After
that, a new tag would be great.

-Richard

**Comment by rjones30** [comment]
Mark,

The RFtime update has been merged, so the current Master hdgeant4 is ready
for tagging.

-Richard

**Comment by markito3** [comment]
Tagged version 1.3.0 yesterday.
