### ISSUE TITLE
Request for DGeometry access for DIRC positions in GlueXPrimaryGeneratorAction

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/HDGeant4#53]
To generate Look Up Tables for the DIRC reconstruction we need access to geometric positions of detector elements from the HDDS xml file.  Richard suggested this should be provided by access to the Geometry class we utilize in sim-recon, so this is the request for such a feature.

**Comment by rjones30** [comment]
This feature is already available to you in HDGeant4. For an example of how to use it, see the GlueXSensitiveDetectorDIRC constructor in the GlueXSensitiveDetectorDIRC.cc source file. The relevant section is here:
   jana::JCalibration *jcalib = japp->GetJCalibration(run_number);
This line gets a JCalibration object, whereas you want a JGeometry object right? Then you should do:
  jana::JGeometry *jgeom = japp->GetJGeometry(run_number);
I presume that you are building these lookup tables PRIOR to the start of tracking? If so, you should do it right here in the constructor and save the results to static read-only members that can be accessed by all of the threads. There is a separate GlueXSensitiveDetectorDIRC for each thread, so initializing these tables once, when instanceCount==0 makes the most sense. Just make sure you access them readonly from the tracking code and there should be no contention between threads.

I don't know why you would need DGeometry and not just JGeometry, but if you want that then you can just use dynamic_cast to cast the japp pointer to DApplication instead of JApplication and then invoke GetDGeometry instead of GetJGeometry. If there are further questions, let me know.

**Comment by jrstevenjlab** [comment]
Wow, I'm not sure how I missed this before.  Closing the issue...
