### ISSUE TITLE
Problems with FDC reconstruction

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/HDGeant4#54]
Justin, Simon, and Thomas noted that there are few tracks reconstructed in the forward direction.  Although the total number of FDC hits was basically consistent between the two simulations, there is a large difference in the number of hits matched to tracks.  For example, we look at single protons with p=4 GeV/c at theta = 4 degrees [see: 
[dc_hits.pdf](https://github.com/JeffersonLab/HDGeant4/files/2204356/dc_hits.pdf)]

Running the FDC_Efficiency plugin showed that the time distributions in the various packages were more-or-less similar, but the residual distributions were quite different, see for plane 1: 
[resid2d.pdf](https://github.com/JeffersonLab/HDGeant4/files/2204381/resid2d.pdf)

Could there be a rotation or other difference in geometry of the packages?

**Comment by zihlmann** [comment]
It is clearly an issue with the timing in the FDC. The two plots show the wirebased and timebased
tracking of an event. The timebased tracking is off losing all CDC hits!
![geant4_wirebased](https://user-images.githubusercontent.com/13365259/43010468-8f42dc72-8c0e-11e8-85e4-bdaaf70c5e07.gif)
![geant4_timebased](https://user-images.githubusercontent.com/13365259/43010469-8f519d3e-8c0e-11e8-982a-c924fcf6ac32.gif)

**Comment by sdobbs** [comment]
Attached are some distributions of the per-plane timing distributions for track hits from FDC_Efficiency.  There is some differences in the gross timing distributions, which are not large, but maybe it could cause this effect.  Thomas' study should give more complete results:

FDC cathode hit times: [fdc_cathode_time.pdf](https://github.com/JeffersonLab/HDGeant4/files/2215571/fdc_cathode_time.pdf)
FDC wire hit times: [fdc_wire_time.pdf](https://github.com/JeffersonLab/HDGeant4/files/2215572/fdc_wire_time.pdf)
FDC pseudo hit times: [fdc_psuedo_time.pdf](https://github.com/JeffersonLab/HDGeant4/files/2215573/fdc_psuedo_time.pdf)

Blue: HDGeant,  Red: HDGeant4

**Comment by T-Britton** [comment]
Understood.  For completeness here are 2 gifs:

![g3](https://user-images.githubusercontent.com/23260420/43337357-a50231d2-91a1-11e8-9b01-8b096094ba75.gif)
![g4](https://user-images.githubusercontent.com/23260420/43337361-a69f1b22-91a1-11e8-9422-4bd5f0eafb36.gif)

**Comment by rjones30** [comment]
I just submitted a pull request that I believe resolves the core issue being reported here. There may be other issues remaining, but this fix should make the forward track efficiency comparable between hdgeant and hdgeant4.

What was the bug?

The code was copied pretty much line-for-line from the hdgeant fdc hits code, except that quantities like 3-vectors that are arrays in the c code become objects in the c++ code. Code conversion in this direction is usually pretty safe, but in this case there was a well-designed programmer's snare in the c code. Consider this brief block of code in hitFDC.c:
        if (AddFDCAnodeHit(ahits,layer,ipart,track,xwire,xlocal,dE,t,
                   &tdrift)){
          AddFDCCathodeHits(PackNo,xwire,xlocal[1],tdrift,n_p,track,ipart,
                chamber,module,layer,global_wire_number);
        }
Looking at that, you see the same array xlocal being passed by pointer to AddFDCAnodeHit and then in the next line element 2 of the same array is passed to AddFDCCathodeHits. What is tricky about this is that AddFDCAnodeHit actually modifies the second element of the xlocal array, so that xlocal changes between the entry and return from AddFDCAnodeHit. Since this is supposed to be the DOCA that was computed earlier in the code, I never imagined that it might be overwritten by the anode wire hits code. WRONG.

Please have pull this fix, rebuild, and check if this fixes this issue. 

In debugging this, I came across several issues with the tracking that I think should be looked into at some point. One of them was in the hdgeant simulation itself, where the DOCA was incorrectly computed in the FDC for nearly half of the hits!! This has been submitted in a separate pull request. There are others that I might come back and look into at some later point, related to the failure of the tracking to correctly find the right way to thread the fdc hits left-right ambiguity, even when multiple scattering and decays are disabled. I also see very bad resolution in the fdc for large drift times when I look in the hdview2 track debugger. By very bad I mean like 700-800 microns sigma. I don't know if this is a bug in the event display or in the tracking, but I suspect the latter. For the time being I am leaving it alone because it appears the same way looking at either the hdgeant or hdgeant4 output.

**Comment by jrstevenjlab** [comment]
Thanks for the fix Richard.  I ran a small sample of pions with p = 4 GeV and theta = 4 degrees in hdgeant4 after this fix (left) and before this fix (right), see below.  With this fix to FDC hits in hdgeant4, the # of hits on tracks looks much more reasonable than the initial comparison that started this thread.  We should wait for Thomas's G3/G4 comparison before closing the issue, but from a first look this certainly moves in the right direction.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/13242886/43835480-1bffd2b6-9ae0-11e8-9b46-944f0d641696.png">

**Comment by T-Britton** [comment]
Looks fine now... will be reopened upon final checks
