### ISSUE TITLE
Hit Energy Agreement

### ISSUE THREAD

**Issue by ReBarsotti** [JeffersonLab/HDGeant4#89]
Hi all, 
I'm a graduate student at IU, and I've been studying the simulation of the FCAL particularly at low energies. I noticed that the distribution of hit energies for similar generated physics looks different in Geant3 and Geant4 (see the attached plot, note that G4 is the dots and G3 is the histogram.). I believe this is causing a difference in efficiency between G3 and G4 with regards to the split-off rejection algorithm. 

I don't fully understand the step processing code, but in looking at it I did notice one strange thing in the code: line 284 in Geant3 and line 204 in Geant4 show dEcorr being multiplied by different constants, and I'm not sure why that would be.

However, the shape of the discrepancy makes me think that maybe the error lies in the exponential part of the energy correlation? (Line 198 in G4, 278 in G3).

Could anyone clarify the reason for the different constants and do you have an idea of where this difference in energy distribution could arise?

<img width="677" alt="ehit_g3g4" src="https://user-images.githubusercontent.com/40772859/53438068-0b2ba780-39cd-11e9-95fc-7bb48a27471c.png">

**Comment by rjones30** [comment]
These kinds of questions are very welcome in this forum! Can I ask your
name? If you wouldn't mind, it would be helpful if you would always sign
your name at the end of a message to this list.

These kinds of differences are normal and expected when comparing G3 and G4
results. If you have the time, please join our HDGeant4 meeting on
bluejeans this afternoon, and share this plot, we will discuss the reasons
for the differences in the code, and the factors that give rise to the
differences between these two curves in this plot. Together we will be able
to come up with a plan for how to follow your investigation further to look
for agreement between the two simulations in the quantities that are most
relevant to physics analysis.
-Richard Jones

**Comment by ReBarsotti** [comment]
I'm afraid that I won't be able to tune in to the HDGeant4 meeting this afternoon, as I will be in classes!
Will there be minutes posted or anything I could review afterwards?

-Rebecca Barsotti

**Comment by rjones30** [comment]
Hello Rebecca,

Let me try in just a few words to summarize the key differences between G3
and G4 in electromagnetic shower propagation. The following assumes that
the two simulations you did were using the same geometry, which may not be
the case since they get their geometries from different places by default.
But if they are properly configured for the same geometry, they are still
different in the way the energy is deposited in the calorimeter blocks.
Here are some high-level overview summary points.

   - electromagnetic calorimeter response depends mostly on what happens to
   the thousands of low-energy particles that live at the ends of the shower
   branches. These are mostly low-energy e+/e- and gamma, but there are
   neutrons and other hadrons occasionally produced as well that affect the
   comparison at the few percent level.
   - hdgeant and hdgeant4 have very different behaviors for low-energy
   gammas and electron/positrons.
      1. hdgeant is less detailed, relying on just a few material
      parameters (radiation length, average nuclear absorption length
of atoms in
      material, average nuclear collision length) whereas hdgeant4 has lookup
      tables that have some amount of atomic structure in them, eg. location of
      absorption edges as a function of Z, individual nuclear cross
sections, etc.
      2. some fraction of the energy in one of these showers ends up in
      hadrons, I don't have a number for this, but the hadronic cross sections
      and modeling of final states is very different in the two simulation
      libraries.
      3. hdgeant4 has a different scheme for deciding when to abandon the
      tracking of a shower particle, based on the remaining range the particle
      has in this particular material, whereas hdgeant simply cuts off
particles
      a fixed energy. This is especially important for gammas, because soft
      gammas have a very large range compared to their energy. This
tends to put
      longer tails on the sides of a shower due to sideways-going soft
gammas in
      hdgeant4 than in hdgeant.
      4. This also means that more of the energy of the shower is converted
      into slow electrons (<300 keV) that do not make Cerenkov light
in hdgeant4,
      relative to hdgeant.

This is why we need different gain constants to make the total observed
shower summed pulse height for a cluster in hdgeant4 and in hdgeant. If you
want to compare them, you cannot compare individual block energies between
hdgeant and hdgeant4 (they agree in the mean at the 5% level, but not much
better than that) but the total summed energy in a cluster should agree
closer to the percent level. At least that was my intent in the tuning I
did of these coefficients you notice are different. You should check if I
did it correctly.

-Richard Jones

**Comment by mashephe** [comment]
Richard and others,

This brings up a question that was touched on at the collaboration meeting.  What is the recommendation for managing differences between Geant3 and Geant4?

Our algorithm is sensitive to hit energies.  It is individual hit energies that either exceed the readout threshold or not and modeling this correctly is necessary.  Assuming that there are no shower level discrepancies between G3 and G4, then this leaves a question of how to proceed from here.

Options:

* tune mcsmear so Geant4+mcsmear matches data -- users of Geant3 will suffer
* have different smearing algorithms for mcsmear depending on input G3 vs. G4
* modify hitFCAL routines in Geant3 to get an input to mcsmear that looks more like G4

Seems like we need a group consensus, as I expect this is not the last time we'll have something like this happen.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808

**Comment by rjones30** [comment]
Hello Matt and all,

You offer 2 possible approaches:

   1. tune mcsmear so Geant4+mcsmear matches data -- users of Geant3 will
   suffer
   2. have different smearing algorithms for mcsmear depending on input G3
   vs. G4
   3. modify hitFCAL routines in Geant3 to get an input to mcsmear that
   looks more like G4

Option 2 is a rat hole that I don't think we get out of. Going this way, we
will end up with such if statements pressing forward into the
reconstruction and eventually the analysis, resulting in two different
competing paths through our libraries for MC. Right now the divergence is
only at the sim stage. Let's confine it there, and work toward eventually
eliminating it.

Options 1 and 3 do not contradict one another. I would say that #1 is the
recommended path, but there is nothing forbidding #3 in addition if someone
is willing to put forth the effort. There will be cases where I don't
understand what G4 is doing where I will do option #3 on my own just as a
path to better understanding. The fact that the models are so different
especially at the hadronic level is an important tool for diagnostics that
I plan to exploit along the way of following #1. But that is just me. I
would say for anyone else who wants to make the best use of time and
effort, #1 is the way to go.

Other opinions?

-Richard J.

**Comment by mashephe** [comment]
Richard and others,

I agree that 1 + 3 is probably the best possible outcome and 2 is not desirable at all.

We don't have a lot of spare cycles and doing 1 is bare minimum.  Another option is 1 + require use of Geant4 for any analysis that needs well-controlled systematic errors.  Geant4 will be required for any DIRC data.  And given that we are only currently looking at 20% of the non-DIRC data, it seems not so much of a stretch to require Geant4 all analyses going forward.  

Of course we learn things from trying to resolve differences, so we want to avoid short circuiting our ability to learn.  But in the end, some of these smearings are rather ad hoc and there is not so much value in repeating this time consuming exercise with two different simulations.

Another general comment regarding strategy:

For many years, it was argued that the decoupling of mcsmear from Geant meant that the transition from G3 to G4 could proceed on its own natural time scale (at least until the DIRC came along and imposed a hard deadline).  People argued that work that went into perfecting mcsmear would translate from G3 to G4.  We now see apparently that isn't true.  To avoid duplication of effort, I would advocate for making the switch as soon as possible, but that is something that needs a more broad consensus than just this thread.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808

**Comment by sdobbs** [comment]
Hi Matt et al.:

At the risk of being repetitive to this audience (maybe we should be having this discussion on the Software list?), I completely agree that we should be spending as much of our effort as possible on HDGeant4.  Since I've been advocating this position for awhile, maybe someone else can summarize the general feeling at the last Software meeting, but I think a consensus in this direction is growing, especially once the next round of checks are complete.

If there is a consensus in the Software group the question to me is:  in what larger forum should this discussion move to?  Or should we just announce that hdgeant will be officially deprecated in, say, 3 months?  =)

---Sean



On Thu, Feb 28, 2019 at 2:50 PM Matthew Shepherd <notifications@github.com<mailto:notifications@github.com>> wrote:

Richard and others,

I agree that 1 + 3 is probably the best possible outcome and 2 is not desirable at all.

We don't have a lot of spare cycles and doing 1 is bare minimum. Another option is 1 + require use of Geant4 for any analysis that needs well-controlled systematic errors. Geant4 will be required for any DIRC data. And given that we are only currently looking at 20% of the non-DIRC data, it seems not so much of a stretch to require Geant4 all analyses going forward.

Of course we learn things from trying to resolve differences, so we want to avoid short circuiting our ability to learn. But in the end, some of these smearings are rather ad hoc and there is not so much value in repeating this time consuming exercise with two different simulations.

Another general comment regarding strategy:

For many years, it was argued that the decoupling of mcsmear from Geant meant that the transition from G3 to G4 could proceed on its own natural time scale (at least until the DIRC came along and imposed a hard deadline). People argued that work that went into perfecting mcsmear would translate from G3 to G4. We now see apparently that isn't true. To avoid duplication of effort, I would advocate for making the switch as soon as possible, but that is something that needs a more broad consensus than just this thread.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone: +1 812 856 5808

**Comment by markito3** [comment]
One question: to what extent is smearing controlled by the CCDB? If all 
smearing were controlled by CCDB, we could manage the differences with 
different variations. I would be surprised if we are completely CCDB 
driven, but the extent to which we are makes a difference in how we 
think of the problem, IMHO.

**Comment by sdobbs** [comment]
If the parameterization does not change, then this is entirely CCDB
driven.  If we need to change the parameterization, or correct for some
other effect, then it should not be a problem to maintain backwards
compatibility.

---Sean

**Comment by nsjarvis** [comment]
Thomas announced that the default on MCWrapper would now be G4.  I didn't
hear any complaints.  If that wasn't the announcement of impending
deprecation, then it was a big hint.

Naomi.

**Comment by sdobbs** [comment]
Hi Rebecca, 
I wanted to follow back up on this after the latest HDGeant4 meeting.  Richard is working on some modifications to HDGeant4, but we also want to make sure we understand what you are looking at. 

Could you please describe how you create your "eHit" distribution?  Is this something like the energy for each FCAL hit from a sample of g p -> p omega, omega -> 3pi simulated events?

**Comment by ReBarsotti** [comment]
Hi Sean,

Yes, I used un-smeared omega MC from a sample of g p -> p omega, omega -> 3pi simulated events.

No cuts or filters were applied, the hit energies were just added in their raw form before clustering or anything was performed on the MC.

Rebecca B.

**Comment by sdobbs** [comment]
OK, thanks for clearing that up!  It's entirely possible that the
difference is due to the interaction of pions in the calorimeter
(hadronic interactions are notoriously difficult to calculate!).
This is next on our list to investigate, hopefully we will have
results soon on some more systematic comparisons of charged particle
interactions.

**Comment by sdobbs** [comment]
Following up on conversations at the Collaboration Meeting, this issue is on hold until the updates to the FCAL smearing have been added and the study redone.

**Comment by mashephe** [comment]
To clarify:  "updates to the FCAL smearing" will resolve the issue by using option 1 as a starting point.

**Comment by sdobbs** [comment]
As briefly discussed in today's HDGeant4 meeting, better agreement between data and simulation has been seen, so changes to mcsmear seem to have helped.

See slide 9 in:  https://halldweb.jlab.org/DocDB/0040/004084/001/MC_NeuralNet_Updates.pdf

Waiting for confirmation that this is resolved.

**Comment by sdobbs** [comment]
These changes to the code are merged in, so I'm closing this issue.
