### ISSUE TITLE
matching to start counter

### ISSUE THREAD

**Issue by aaust** [JeffersonLab/HDGeant4#90]
In a sample of exclusive rho events, I see very different distributions for the reconstructed protons that are matched to the start counter. I expect to see most protons around 60 degrees, like seen in hdgeant(3):

![image](https://user-images.githubusercontent.com/8807112/53445577-21f3ed80-3a11-11e9-8cc5-212ae7716266.png)

On the other hand, the histogram for the thrown PID looks fine:

![image](https://user-images.githubusercontent.com/8807112/53445951-0d642500-3a12-11e9-9397-2447484af250.png)

**Comment by rjones30** [comment]
I believe I have traced this down to a mismatch between GlueXSensitiveDetectorStc.cc and hitStart.c in which ccdb table they were getting their calibration constants (propagation speeds, attenuation lengths, etc.) from. The GlueXSensitiveDetectorStc.cc code was written to get the propagation speeds from the table /START_COUNTER/propagation_speed whereas the code in hitStart.c was fetching them from /START_COUNTER/propagation_time_corr. Both tables have the same set of 6 columns, one counter per row, but the contents are different. I don’t know what both are needed, but for the moment I just want the two simulations to use the same set, so I introduced a fix to the hdgeant4 code and left the hdgeant code unchanged. I chose this option so that any work that has been done heretofore on matching between real data and simulations has been based on hdgeant, so we should start off with hdgeant4 replicating the same behaviors, and develop it from there.

Below I show a single plot that is similar to what I showed above, except that the pion polar angle is now spread over the full range 0o - 120o. This smears out the start counter timing quite a bit, but the comparison clearly shows that hdgeant (black points) and hdgeant4 (red points) now agree on the start counter timing. I submitted a pull request for this change, and await confirmation from Alex A. that the inconsistency he saw in the rho0,p simulations at the level of matched start counter hits is now resolved.

![image](https://user-images.githubusercontent.com/7832920/53525950-f9233500-3ab0-11e9-874b-639281d08c6a.png)

**Comment by aaust** [comment]
It does look much better now:
![image](https://user-images.githubusercontent.com/8807112/53529096-a601b000-3ab9-11e9-8542-2a651d1a6d9a.png)
Thank you for the quick fix!

**Comment by sdobbs** [comment]
Yes, /START_COUNTER/propagation_time_corr is the correct table.

Some day I will get the ability to deprecate CCDB tables...

**Comment by aaust** [comment]
Actually, a few of the reported differences have become a lot less striking:
- proton theta (page 526)
- vertex deltaT (page 113)
- overall track timing (page 872, 976), the remaining difference comes from the BCAL (page 873)

I uploaded a new version of the comparison [here](https://halldweb.jlab.org/talks/2019/Independent_rho_G3_G4_STfix.pdf)

The effect on the overall acceptance is very small.
